"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { Header } from "@/components/header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Copy, QrCode, ArrowLeft, CheckCircle, AlertTriangle, Wallet } from "lucide-react"
import Link from "next/link"

export default function DepositPage() {
  const router = useRouter()
  const [copied, setCopied] = useState(false)
  const [showQR, setShowQR] = useState(false)

  // USDT deposit address (this would be generated by your backend)
  const depositAddress = "TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE"

  useEffect(() => {
    // Redirect if not signed in
    const isSignedIn = localStorage.getItem("isSignedIn") === "true"
    if (!isSignedIn) {
      router.push("/signin")
    }
  }, [router])

  const copyAddress = () => {
    navigator.clipboard.writeText(depositAddress)
    setCopied(true)
    setTimeout(() => setCopied(false), 3000)
  }

  const depositInstructions = [
    "Copy the USDT (TRC-20) deposit address below",
    "Send USDT from your wallet to this address",
    "Wait for network confirmation (usually 1-3 minutes)",
    "Your balance will be updated automatically",
    "Minimum deposit: $20 USDT",
  ]

  const handleDepositComplete = () => {
    router.push("/dashboard")
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container py-8">
        <div className="max-w-2xl mx-auto">
          <div className="mb-6">
            <Button variant="ghost" asChild className="mb-4">
              <Link href="/dashboard">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back to Dashboard
              </Link>
            </Button>
            <h1 className="text-3xl font-bold mb-2">Deposit Funds</h1>
            <p className="text-muted-foreground">Add USDT to your investment account</p>
          </div>

          <div className="space-y-6">
            {/* Deposit Method */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Wallet className="h-5 w-5 mr-2" />
                  Cryptocurrency Deposit
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between p-4 border rounded-lg bg-muted/30">
                  <div className="flex items-center space-x-3">
                    <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                      <span className="text-green-600 font-bold">₮</span>
                    </div>
                    <div>
                      <div className="font-semibold">USDT (TRC-20)</div>
                      <div className="text-sm text-muted-foreground">Tether USD on TRON Network</div>
                    </div>
                  </div>
                  <Badge variant="secondary">Recommended</Badge>
                </div>
              </CardContent>
            </Card>

            {/* Instructions */}
            <Card>
              <CardHeader>
                <CardTitle>How to Deposit</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {depositInstructions.map((instruction, index) => (
                    <div key={index} className="flex items-start space-x-3">
                      <div className="w-6 h-6 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                        <span className="text-xs font-medium text-primary">{index + 1}</span>
                      </div>
                      <p className="text-sm">{instruction}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Deposit Address */}
            <Card>
              <CardHeader>
                <CardTitle>Your USDT Deposit Address</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <Alert>
                  <AlertTriangle className="h-4 w-4" />
                  <AlertDescription>
                    <strong>Important:</strong> Only send USDT (TRC-20) to this address. Sending other cryptocurrencies
                    may result in permanent loss.
                  </AlertDescription>
                </Alert>

                <div className="space-y-3">
                  <div className="p-4 bg-muted/30 rounded-lg border-2 border-dashed">
                    <div className="text-center">
                      <div className="font-mono text-sm break-all mb-3 p-3 bg-background rounded border">
                        {depositAddress}
                      </div>
                      <div className="flex justify-center space-x-2">
                        <Button onClick={copyAddress} variant="outline" size="sm">
                          <Copy className="h-4 w-4 mr-2" />
                          {copied ? "Copied!" : "Copy Address"}
                        </Button>
                        <Button onClick={() => setShowQR(!showQR)} variant="outline" size="sm">
                          <QrCode className="h-4 w-4 mr-2" />
                          {showQR ? "Hide QR" : "Show QR"}
                        </Button>
                      </div>
                    </div>
                  </div>

                  {showQR && (
                    <div className="text-center p-6 bg-muted/30 rounded-lg">
                      <div className="w-48 h-48 bg-white rounded-lg mx-auto mb-4 flex items-center justify-center border">
                        <div className="text-center">
                          <QrCode className="h-16 w-16 text-muted-foreground mx-auto mb-2" />
                          <p className="text-xs text-muted-foreground">QR Code would appear here</p>
                          <p className="text-xs text-muted-foreground">in production</p>
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground">Scan with your wallet app</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Network Information */}
            <Card>
              <CardHeader>
                <CardTitle>Network Information</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <div className="text-muted-foreground">Network</div>
                    <div className="font-semibold">TRON (TRC-20)</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Confirmations</div>
                    <div className="font-semibold">1 confirmation</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Processing Time</div>
                    <div className="font-semibold">1-3 minutes</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Minimum Deposit</div>
                    <div className="font-semibold">$20 USDT</div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Recent Deposits */}
            <Card>
              <CardHeader>
                <CardTitle>Recent Deposits</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center justify-between p-3 border rounded-lg">
                    <div className="flex items-center space-x-3">
                      <CheckCircle className="h-5 w-5 text-green-500" />
                      <div>
                        <div className="font-medium">$500.00 USDT</div>
                        <div className="text-sm text-muted-foreground">Jan 15, 2024 • 10:30 AM</div>
                      </div>
                    </div>
                    <Badge variant="secondary" className="bg-green-100 text-green-800">
                      Completed
                    </Badge>
                  </div>

                  <div className="flex items-center justify-between p-3 border rounded-lg">
                    <div className="flex items-center space-x-3">
                      <CheckCircle className="h-5 w-5 text-green-500" />
                      <div>
                        <div className="font-medium">$1,000.00 USDT</div>
                        <div className="text-sm text-muted-foreground">Jan 12, 2024 • 2:15 PM</div>
                      </div>
                    </div>
                    <Badge variant="secondary" className="bg-green-100 text-green-800">
                      Completed
                    </Badge>
                  </div>

                  <div className="text-center py-4">
                    <Button variant="outline" size="sm">
                      View All Transactions
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Deposit Complete Button */}
            <Card>
              <CardHeader>
                <CardTitle>Deposit Complete?</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground mb-4">
                  Once your deposit has been confirmed on the blockchain, click the button below to proceed to your
                  dashboard.
                </p>
                <Button onClick={handleDepositComplete} className="w-full" size="lg">
                  <CheckCircle className="h-4 w-4 mr-2" />I Have Deposited
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}
